In [82]:
import pandas as pd
import matplotlib.pyplot as plt
imgen_event_idt sys
import hashlib
import numpy as np

def get_md5(src):
    m2 = hashlib.md5()   
    m2.update(src.encode('utf-8'))   
    return m2.hexdigest()
def gen_event_id(x):
    if x==1:
        return get_md5(str(np.random.rand()))
    else:
        return 0

In [56]:
import pandas as pd
data_path=path="../data/demo_data/metric/Twitter_volume_UPS.csv"
metric_data_df=pd.read_csv(data_path)

In [58]:
data=metric_data_df["value"].values.reshape([-1,1])
data
# table = pd.concat([metric_data_df["value"]], axis=1)
# table

array([[2],
       [2],
       [4],
       ...,
       [2],
       [3],
       [3]])

In [61]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor
X = [[-1.1], [0.2], [10], [0.3]]
clf = LocalOutlierFactor(n_neighbors=2)
label=clf.fit_predict(data)
event=[]
for i in label:
    if i==1:
        event.append(0)
    else:
        event.append(1)
metric_data_df["event"]=event

In [67]:
dt = pd.date_range(start="20210101",periods=len(metric_data_df) ,freq="5s")  # freq="D"表示频率为每一天
metric_data_df["ts"]=dt

In [83]:
metric_data_df["event"]=metric_data_df["event"].apply(gen_event_id)

In [85]:
metric_data_df[metric_data_df["event"]!=0]

,timestamp,value,event,ts
1186,2015-03-03 00:32:53,33,1c91756674b441a16c08dc256a614daa,2021-01-01 01:38:50
1288,2015-03-03 09:02:53,76,0293634f699734aeeba17ab1fbc89743,2021-01-01 01:47:20
1437,2015-03-03 21:27:53,95,bc1d83686dd9af169dbaa2f2c9d5f853,2021-01-01 01:59:45
1442,2015-03-03 21:52:53,45,dce7af4973b2c8474cade713c9058fd2,2021-01-01 02:00:10
1599,2015-03-04 10:57:53,52,3dd0e8b527ee458fc1d6d698ab50483f,2021-01-01 02:13:15
1607,2015-03-04 11:37:53,162,bb101765b8c2531c635d0b55de1abaf1,2021-01-01 02:13:55
1611,2015-03-04 11:57:53,71,2f816efca0ac65c39fa293effb36f6c5,2021-01-01 02:14:15
1692,2015-03-04 18:42:53,52,068ae0e9a29b44c475a1bc0797ed0390,2021-01-01 02:21:00
1724,2015-03-04 21:22:53,133,e42878314b4bcfb8df5e0311a9d7f912,2021-01-01 02:23:40
1727,2015-03-04 21:37:53,160,c5cc5463ebe2c0d981624833ebc07947,2021-01-01 02:23:55
1938,2015-03-05 15:12:53,54,696d46ce464a62fbaed0d8299970eb89,2021-01-01 02:41:30
1963,2015-03-05 17:17:53,157,843f45d27f6c9a1298c95c5e79c511a5,2021-01-01 02:43:35
2021,2015-03-05 22:07:53,162,ffd3214e53661402fab00753dbddbe6f,2021-01-01 02:48:25
2089,2015-03-06 03:47:53,67,5edace4ce691eb18a32f5d31c1cba6df,2021-01-01 02:54:05
2245,2015-03-06 16:47:53,195,396d7a60688be51eec01b53a581940ca,2021-01-01 03:07:05
2247,2015-03-06 16:57:53,203,9992864ae9655897ffe828a530f24c78,2021-01-01 03:07:15
2745,2015-03-08 10:27:53,197,8295d900b4180a180bdf7433ee9fac23,2021-01-01 03:48:45
2747,2015-03-08 10:37:53,193,8f7a5e5684467039b29ba122e0262a1c,2021-01-01 03:48:55
2848,2015-03-08 19:02:53,203,b94c0ef4ccf5ee72034d1e25d1124d81,2021-01-01 03:57:20
2851,2015-03-08 19:17:53,28,fcc62321daac535eaacf385405062aff,2021-01-01 03:57:35
2900,2015-03-08 23:22:53,189,ea7c26d8dc46a157a5788c9e89d4a97f,2021-01-01 04:01:40
3307,2015-03-10 09:17:53,165,1c4a8f8a206b4b870b857f028391f32a,2021-01-01 04:35:35
3342,2015-03-10 12:12:53,177,0cd511a91dbec0f5a8a4205a565fa242,2021-01-01 04:38:30
3412,2015-03-10 18:02:53,209,bb91d8a6b454de50fe3220e43eb5db20,2021-01-01 04:44:20
3778,2015-03-12 00:32:53,84,0481e1ba793cd55b25f0defe07bcea3c,2021-01-01 05:14:50
3825,2015-03-12 04:27:53,76,48fd171027f400d75e7f6d0430ec9dcb,2021-01-01 05:18:45
3826,2015-03-12 04:32:53,93,ee8a2267216a1d274c3ec5cd03ed2134,2021-01-01 05:18:50
3918,2015-03-12 12:12:53,91,1de9f80fc7560ed2b31c79f5bf28884f,2021-01-01 05:26:30
3922,2015-03-12 12:32:53,126,f016ef608a7fb0a65eafb9a3d50c24fd,2021-01-01 05:26:50
4045,2015-03-12 22:47:53,108,5b6d43a808f789e393180a4789d35fba,2021-01-01 05:37:05
4050,2015-03-12 23:12:53,54,666ec71be9078db5642cc4df17bc0c08,2021-01-01 05:37:30
4161,2015-03-13 08:27:53,117,9617e8eb5a9201ff55743e6faa858f21,2021-01-01 05:46:45
4366,2015-03-14 01:32:53,148,3be52bcf145cf2649c4e1c672b66b334,2021-01-01 06:03:50
4453,2015-03-14 08:47:53,50,590709611b5187244ca4cc8f8d2c0a25,2021-01-01 06:11:05
4458,2015-03-14 09:12:53,152,cefe8dfb0a401b864950df1f73144e28,2021-01-01 06:11:30
4547,2015-03-14 16:37:53,42,74f7831f9c9b23de7ccfc19dc2b36255,2021-01-01 06:18:55
4550,2015-03-14 16:52:53,152,49b4bb6474c7294f600cb4a2c3cf068c,2021-01-01 06:19:10
4598,2015-03-14 20:52:53,160,308b8d51580ac9e12a06828698d9287e,2021-01-01 06:23:10
5031,2015-03-16 08:57:53,100,49b8b6e41a174a51d7f72bfe0db381cb,2021-01-01 06:59:15
5535,2015-03-18 02:57:53,189,91acee840691feafb6fef7292490d906,2021-01-01 07:41:15
7443,2015-03-24 17:57:53,26,688dccb344a871543b8f27525fd325dd,2021-01-01 10:20:15
7524,2015-03-25 00:42:53,200,4a23b6b0ed1cd5d166c198a6b6d15eab,2021-01-01 10:27:00
7526,2015-03-25 00:52:53,231,e1b9b436a16939600f615107b7beeb36,2021-01-01 10:27:10
7527,2015-03-25 00:57:53,155,c0006fe0f22efcf7629e5942e066a65c,2021-01-01 10:27:15
7914,2015-03-26 09:12:53,214,04bc221430ac90110557a8e5abb5642e,2021-01-01 10:59:30
8792,2015-03-29 10:22:53,200,168b781df32cd2962bba367d4f2b61c4,2021-01-01 12:12:40
8795,2015-03-29 10:37:53,145,44ae3c8679e11a454ce5b42efe337a85,2021-01-01 12:12:55
9862,2015-04-02 03:32:53,100,6c6b5234d0be30813d6fa05c6835fef6,2021-01-01 13:41:50
9975,2015-04-02 12:57:53,67,eb719475cf99c1b232e10146cf62be7e,2021-01-01 13:51:15
10190,2015-04-03 06:52:53,204,ef2d2970b9902e3ef46b7c32e3780668,2021-01-01 14:09:10
10501,2015-04-04 08:47:53,84,bb88b6f3338f2602e275fd55cdfc97e7,2021-01-01 14:35:05
11152,2015-04-06 15:02:53,42,2040ff2d1f49c886e54f3da5334e076a,2021-01-01 15:29:20
11956,2015-04-09 10:02:53,197,6a9d842b8e67fd395c1e193f075b0093,2021-01-01 16:36:20
13759,2015-04-15 16:17:53,193,3b2e734e06244fa33f4d7d5ca9fed2e6,2021-01-01 19:06:35
13762,2015-04-15 16:32:53,144,79268b5d005b4a46765ba6bdf08bd263,2021-01-01 19:06:50
14021,2015-04-16 14:07:53,64,0f1ddb89c34ee40dede03c05f17780e0,2021-01-01 19:28:25
14348,2015-04-17 17:22:53,49,97e499e1ce8928922cd8aabf817dfd20,2021-01-01 19:55:40
14657,2015-04-18 19:07:53,209,ea5b17a7bd360f2d6525c48d37ccac32,2021-01-01 20:21:25

In [87]:
metric_data_df=metric_data_df[["ts","event","value"]]
metric_data_df.to_csv("../data/demo_data/metric/metric_with_event.csv")

In [19]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import LocalOutlierFactor

print(__doc__)

np.random.seed(42)

# Generate train data
X_inliers = 0.3 * np.random.randn(100, 2)
X_inliers = np.r_[X_inliers + 2, X_inliers - 2]

# Generate some outliers
X_outliers = np.random.uniform(low=-4, high=4, size=(20, 2))
X = np.r_[X_inliers, X_outliers]

Automatically created module for IPython interactive environment

In [48]:
>>> import numpy as np
>>> from sklearn.neighbors import LocalOutlierFactor
>>> X = [[-1.1], [0.2], [10], [0.3]]
>>> clf = LocalOutlierFactor(n_neighbors=2)
>>> clf.fit_predict(X)
clf.negative_outlier_factor_

array([-0.98214286, -1.03703704, -7.09325397, -0.98214286])